itapps/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('itreporting/', include('itreporting.urls')),
    path('', include('itreporting.urls')), 
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name = 'profile'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itreporting/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
app_name = 'itreporting'

urlpatterns = [
    path('home/', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('report/', PostListView.as_view(), name = 'report'),  
    path('issues/<int:pk>', PostDetailView.as_view(), name = 'issue-detail'),
    path('issue/new', PostCreateView.as_view(), name = 'issue-create'),
    path('issues/<int:pk>/update/', PostUpdateView.as_view(), name = 'issue-update'),
    path('issue/<int:pk>/delete/', PostDeleteView.as_view(), name = 'issue-delete'),
]

itreporting/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django import forms
from django.core.validators import EmailValidator

class Issue(models.Model):
    type = models.CharField(max_length=100, choices=[('Hardware', 'Hardware'), ('Software', 'Software')])
    room = models.CharField(max_length=100)
    urgent = models.BooleanField(default=False)
    details = models.TextField()
    date_submitted = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    author = models.ForeignKey(User, related_name='issues', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.type} Issue in {self.room}'

    def get_absolute_url(self):
        return reverse('itreporting:issue-detail', kwargs={'pk': self.pk})


class Contact(forms.Form):
    Firstname = forms.CharField(max_length=50)
    Surename = forms.CharField(max_length=50)
    Email = forms.CharField(validators=[EmailValidator()])
    Address = forms.CharField(max_length=50)
    Phonenumber = forms.CharField(max_length=11)
    Message = forms.CharField(widget=forms.Textarea)

class Module(forms.Form):
    modulename = forms.CharField(max_length=50)
    Code = forms.CharField(max_length=50)
    Credit = forms.CharField(max_length=50)
    AddCategory = forms.CharField(max_length=50)
    Phonenumber = forms.CharField(max_length=11)
    Description = forms.CharField(widget=forms.Textarea)
    Availability = forms.CharField(max_length=50)
    Course = forms.CharField(max_length=50)

class Contact(forms.Form):
    Firstname = forms.CharField(max_length=50)
    Surename = forms.CharField(max_length=50)
    Email = forms.CharField(validators=[EmailValidator()])
    Address = forms.CharField(max_length=50)
    Phonenumber = forms.CharField(max_length=11)
    Message = forms.CharField(widget=forms.Textarea)

itreporting/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Issue
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import DeleteView
from .models import Contact
from django.core.mail import EmailMessage
import requests


def home(request):

    url = 'https://api.openweathermap.org/data/2.5/weather?q={},{}&units=metric&appid={}'
    cities = [('Sheffield', 'UK'), ('Melaka', 'Malaysia'), ('Bandung', 'Indonesia')]
    weather_data = []
    api_key = '1f9c0d6aa16a263969692d60d8801e9e'

    for city in cities:
        city_weather = requests.get(url.format(city[0], city[1], api_key)).json() # Request the API data and convert the JSON to Python data types
        #print(city_weather)
        
    weather = {
        'city': city_weather['name'] + ', ' + city_weather['sys']['country'],
        'temperature': city_weather['main']['temp'],
        'description': city_weather['weather'][0]['description']
    }   
    weather_data.append(weather) # Add the data for the current city into our list
    return render(request, 'itreporting/home.html', {'title': 'Homepage', 'weather_data': weather_data})


#def home(request):
    #return render(request, 'itreporting/home.html', {'title': 'Welcome'})

#def contact(request):
    #return render(request, 'itreporting/contact.html', {'title': 'Contact'})

def about(request):
    return render(request, 'itreporting/about.html', {'title': 'About'})

def report(request):
    daily_report = {'issues': Issue.objects.all(), 'title': 'Issues Reported'}
    return render(request, 'itreporting/report.html', daily_report)

def contact(request):
    if request.method == "POST":
        form = Contact(request.POST)
        if form.is_valid():
            Firstname = form.cleaned_data["Firstname"]
            Surename = form.cleaned_data["Surename"]
            Email = form.cleaned_data["Email"]
            Address = form.cleaned_data["Address"]
            Phonenumber = form.cleaned_data["Phonenumber"]
            Message = form.cleaned_data["Message"]
            email_message = EmailMessage(
                subject=f"Contact Form from {Firstname,Surename}",
                body=Message,
                from_email= Email,
                to=["noreply@SHU.com"],
                reply_to=[Email],
            )
            email_message.send()
            messages.success(request, "Your message has been received!")
            form = Contact() 

        else:
            messages.error(request, "There was an error with your submission.")
    else:
        form = Contact()

    return render(request, 'itreporting/contact.html', {'form': form, 'title': 'Contact'})

class PostDetailView(DetailView):
    model = Issue
    template_name = 'itreporting/issue_detail.html'


class PostListView(ListView):
    model = Issue
    ordering = ['-date_submitted']
    template_name = 'itreporting/report.html'
    context_object_name = 'issues'
    paginate_by = 10 # Optional pagination


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Issue
    fields = ['type', 'room', 'urgent', 'details']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    

#class PostUpdateView(LoginRequiredMixin, UpdateView):
    #model = Issue
    #fields = ['type', 'room', 'details']


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Issue
    fields = ['type', 'room', 'details']
    def test_func(self):
        issue = self.get_object()
        return self.request.user == issue.author
    
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Issue
    success_url = '/report'
    def test_func(self):
        issue = self.get_object()
        return self.request.user == issue.author
    

itreporting/templates/itreporting/about.html
{% extends "itreporting/base.html" %}
{% block content %}
<h1>About us</h1>
{% endblock %}
<body>
    <h1>Welcome to Student IT Services</h1>
</body>

</html>

itreporting/templates/itreporting/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
    <title>Sheffield Hallam University - {{title}}</title>
</head>
{% if messages %}
<div class="container mt-3">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}

<body>
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'itreporting:home' %}">Sheffield Hallam University</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                        aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{% url 'itreporting:home'%}">Home</a>
                            <a class="nav-item nav-link" href="{% url 'itreporting:about'%}">About</a>
                            <a class="nav-item nav-link" href="{% url 'itreporting:report'%}">Report</a>
                            <a class="nav-item nav-link" href="{% url 'itreporting:contact'%}">Contact</a>
                            <div class="navbar-nav">
                                <div class="navbar-nav ml-auto">
                                    {% if user.is_authenticated %}
                                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                                    <a class="nav-item nav-link" href="{% url 'itreporting:issue-create' %}">Report New
                                        Issue</a>
                                    <form method="post" id="frm_logout" action="{% url 'logout' %}"
                                        style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="nav-item nav-link"
                                            style="background:none; border:none; cursor:pointer;">Logout</button>
                                    </form>
                                    {% else %}
                                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
            </nav>
        </header>
        <div class="row">
            <div class="col-md-8">
                {% block content %}{% endblock %}
            </div>
            {% block sidebar %} 

            <div class="col-md-4"> 

                    <h3>Current Weathers</h3> 
            
                    <p class='text-muted'>Cities across United Kingdom 
            
                        <ul class="list-group"> 
            
                                {% for weather in weather_data %} 
            
                                    <li class="list-group-item list-group-item-light">{{ weather.city }}: {{ weather.description }}, {{ weather.temperature }}&deg;C</li> 
            
                                {% endfor %} 
            
                        </ul> 
            
                    </p> 
            
            </div> 
            
            {% endblock sidebar %} 
        </div>
    </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
    <script>
        window.setTimeout(function () {
            const alerts = document.querySelectorAll('.alert');
            alerts.forEach(alert => {
                alert.classList.add('fade');
                setTimeout(() => alert.remove(), 500); // Removes element after fading out
            });
        }, 5000); // Adjust the delay as needed (5000 ms = 5 seconds)
    </script>
</body>

</html>

itreporting/templates/itreporting/blank.html
{% extends "itreporting/base.html" %}

{% block content %}
  <h3>Sheffield Hallam University</h3>
  <div>
    <h1><p>Sheffield Hallam University</p></h1>
  </div>
{% endblock %}

itreporting/templates/itreporting/contact.html
{% extends "itreporting/base.html" %}

{% block content %}
<h1><p>Contact Us</p></h1>
<form method="post">
    <h1></h1>
    {% csrf_token %}
    {% for field in form %}
        <div>
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.errors %}
                <div style="color: red;">
                    {{ field.errors }}
                </div>
            {% endif %}
        </div>
    {% endfor %}
    <button type="submit">Submit</button>
</form>
{% endblock %}

itreporting/templates/itreporting/home.html
{% extends "itreporting/base.html" %}

{% block content %}
  <h3>Sheffield Hallam University</h3>
  <div>
    <h1><p>Sheffield Hallam University</p></h1>
  </div>
{% endblock %}

itreporting/templates/itreporting/issue_confirm_delete.html
{% extends "itreporting/base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete IT issue</legend>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'itreporting:issue-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

itreporting/templates/itreporting/issue_detail.html
<!DOCTYPE html>
<html>

<head>
    <title>Modules</title>
</head>

<body>
    <h1>Modules</h1>
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ object.author.profile }}</a>
                <small class="text-muted">{{ object.date_submitted }}</small>
            </div>
            <h2 class="article-title">{{ object.type }} Issue in
                Room {{object.room}}</h2>
            <p class="article-content">{{ object.details }}</p>
        </div>
    </article>
</body>

</html>

itreporting/templates/itreporting/issue_form.html
{% extends "itreporting/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="borer-bottom mb-4"> Report IT Issue </legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">Are you already Registered? <a class="ml-2" href="#">Login
            </a></small>
    </div>
</div>
{% endblock content %}

itreporting/templates/itreporting/report.html
{% extends "itreporting/base.html" %}

{% block content %}
    <h1>Courses</h1>
    {% for issue in issues %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ issue.author.profile }}</a>
                    <small class="text-muted">{{ issue.date_submitted }}</small>
                </div>
                <h2>
                    <a class="article-title" href="{% url 'itreporting:issue-detail' issue.id %}">{{ issue }}</a>
                </h2>
                <p class="article-content">{{ issue.details }}</p>
            </div>
        </article>
    {% endfor %}

    {% if is_paginated %}
        <div class="pagination">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}